config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "transports#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :transports, only: [:home, :show, :new, :edit, :update, :create, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:show, :edit, :update, :detroy]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :transport

  validates :reservation_end, comparison: { greater_than: :reservation_begin }
  # validates_comparison_of :reservation_begin, less_than: :reservation_end, greater_than: -> { Date.today }
end

app/models/transport.rb
class Transport < ApplicationRecord
  has_many :users
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :brand, presence: true
  validates :horse, presence: true
  validates :year, presence: true

  include PgSearch::Model
    pg_search_scope :search_by_brand_and_year,
  against: [ :brand, :year ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :transports
  validates :email, presence: true
  validates :encrypted_password, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # add this line like in the lesson of today
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :set_bookings, only: [:show, :edit, :update, :destroy]

  def new
    @booking = Booking.new
    @transport = Transport.find(params[:transport_id])
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.transport = Transport.find(params[:transport_id])
    @booking.user_id = current_user.id
    @booking.save

    # No need for app/views/bookings/create.html.erb
    redirect_to booking_path(@booking)
  end

  def edit
  end

  def update
    if @booking.update(booking_params)
      redirect_to booking_path(@booking)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to transport_path(@booking.transport), status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:reservation_begin, :reservation_end, :user_id, :transport_id)
  end
  def set_bookings
    @booking = Booking.find(params[:id])
  end
end

app/controllers/transports_controller.rb
class TransportsController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :set_transports, only: [:show, :edit, :update, :destroy]

  def home
    if params[:query].present?
      @transports = Transport.search_by_brand_and_year(params[:query])
    else
      @transports = Transport.all
    end
  end

  def show
  end

  def new
    @transport = Transport.new
  end

  def create
    @transport = Transport.new(transport_params)
    @transport.user_id = current_user.id
    if @transport.save
      redirect_to transport_path(@transport)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @transport.update(transport_params)
      redirect_to transport_path(@transport)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @transport.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def transport_params
    params.require(:transport).permit(:brand, :horse, :year, :price, :user_id, photos: [])
  end

  def set_transports
    @transport = Transport.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Change transport</h1>

<div class="container">
  <%= simple_form_for [@transport, @booking] do |f| %>
    <%= f.input :reservation_begin, as: :date, html5: true %>
    <%= f.input :reservation_end, as: :date, html5: true %>
    <%= f.button :submit, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>Transport reservation</h1>

<div class="container">
  <%= simple_form_for [@transport, @booking] do |f| %>
    <%= f.input :reservation_begin, as: :date, html5: true %>
    <%= f.input :reservation_end, as: :date, html5: true %>
    <%= f.button :submit, class: "btn btn-primary"%>
  <% end %>
</div>

app/views/bookings/show.html.erb
    <h1>Booking</h1>

<div class="container">
    <h3> Confirmation number: <%= @booking.id %></h3>
    <p>Start : <%= @booking.reservation_begin %> - End : <%= @booking.reservation_end %></p>

<h2>Transport details :</h2>
  <% if @booking.transport.photos.attached? %>
    <% @booking.transport.photos.each do |photo| %>
        <%= cl_image_tag photo.key %>
    <% end %>
  <% else %>
    <%= 'No Image' %>
  <% end %>
 <p> Brand : <%= @booking.transport.brand %></p>
    <p> Power : <%= @booking.transport.horse %></p>
    <p> Year : <%= @booking.transport.year %></p>
    <p> Price per day : <%= @booking.transport.price %></p>

<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quaerat, recusandae at. Earum incidunt, tenetur sed vel soluta esse optio dignissimos, consectetur quam eum rerum reprehenderit recusandae perferendis exercitationem odit assumenda!
Itaque error optio, alias possimus maiores eligendi nostrum sequi, eos nisi excepturi repellendus ea veniam quasi dolore maxime dolorem temporibus, similique commodi laborum. Veritatis, consequuntur? Doloribus consectetur suscipit error nemo?
Inventore consequuntur fuga porro debitis qui sequi reiciendis culpa unde. Ex, aliquam! Tempore voluptatem, amet corporis repellat vitae assumenda dolorem beatae dolores, voluptatum libero dolore possimus ducimus. Consequuntur, non accusantium.
Officiis distinctio corporis aliquid esse? Incidunt possimus consequatur et. Porro magni dicta cumque sequi numquam dolor, sed doloribus labore, praesentium beatae eum. Laborum repellendus molestias ipsa temporibus voluptates autem sed?
Sequi nemo minima quod sint nulla consequuntur placeat autem voluptates nesciunt ab quos vitae quas perspiciatis impedit natus dolorem culpa, in aliquam corrupti doloribus nam? Nam ducimus rem dolor nostrum?
Exercitationem quae sint quos cupiditate delectus soluta illum dolore quaerat in voluptas ab a vero suscipit inventore natus ipsum expedita, laboriosam saepe! Quae iste earum molestias facilis ab assumenda optio?
Aliquid eos voluptatibus quia ipsam, repellendus sit commodi aliquam non odio dolorum iste officia sint at. Explicabo atque blanditiis quibusdam quas, asperiores rem, laboriosam molestiae voluptates itaque molestias qui maiores.
Qui distinctio cupiditate non aut deleniti ratione dignissimos magni magnam, tenetur quos a at laborum praesentium recusandae neque laboriosam nam explicabo quia sint optio! Et pariatur quibusdam voluptatibus incidunt perferendis?
Cumque, dolores deleniti veniam enim quo consectetur nemo, recusandae officia deserunt, corporis magni quibusdam. Sed, illum minima? Provident delectus et quis voluptates magnam vel vitae at quae atque consequatur. Et.
Iusto nostrum fugiat alias, praesentium maiores iste est optio deleniti. Amet, vitae. Maiores tempora eligendi odit culpa tenetur veniam dicta, aut hic, saepe fugit eos numquam voluptates dolor non assumenda.</p>

  <%= link_to "Home", root_path(@transports), class: "btn btn-primary" %><br />
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KekeTuning</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="icon"
     type="image/png"
     href="https://image.shutterstock.com/image-vector/blue-line-car-automotive-race-600w-1685727928.jpg">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "transports/navbar" %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "transports/footer" %>
  </body>
</html>

app/views/transports/_card.html.erb
<%# <div class="card">
  <div class="card-image"></div>
  <div class="card-text">
    <h2><%= transport.brand %></h2>
    <p>Year : <%= transport.year %></p>
    <h2>Prix : <%= transport.price %> $</h2>
  </div>
<%# </div> %>

app/views/transports/_footer.html.erb
<%# <footer class='d-flex justify-content-around design-footer'>
  <div class="fa-3x" >
    <img src="https://res.cloudinary.com/dojiqdbe4/image/upload/v1677600746/diable1_wubyti.png" class="fa-solid fa-shake" >
  </div>
   <div class="fa-3x" >
    <img src="https://res.cloudinary.com/dojiqdbe4/image/upload/v1677600746/diable1_wubyti.png" class="fa-solid fa-shake" >
  </div>
   <div class="fa-3x" >
    <img src="https://res.cloudinary.com/dojiqdbe4/image/upload/v1677600746/diable1_wubyti.png" class="fa-solid fa-shake" >
  </div>
</footer> %>

 <footer>
  <ul class="footer">
    <div class="f-text">
      <h4>AIDE</h4>
      <li><a href="#">Statut de commande</a></li>
      <li><a href="#">Nous contacter</a></li>
    </div>
    <div id='contact-info'>
      <div class='links'>
        <a href='https://www.twitter.com' target='_blank'>
          <div>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span>
                  <i class="fab fa-twitter"></i>
                </span>
          </div>
        </a>
        <a href='https://www.facebook.com' class='orange-border' target='_blank'>
          <div>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span>
                  <i class="fab fa-facebook-f"></i>
                </span>
          </div>
        </a>
        <a href='https://www.instagram.com' class='orange-background' target='_blank'>
          <div>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            <span>
                  <i class="fab fa-instagram"></i>
                </span>
          </div>
        </a>
      </div>
    </div>
    <div class="fa-3x" >
      <img src="https://res.cloudinary.com/dojiqdbe4/image/upload/v1677600746/diable1_wubyti.png" class="fa-solid fa-shake" >
    </div>
  </ul>
</footer>

app/views/transports/_form.html.erb
<%= simple_form_for(transports) do |f| %>
  <%= f.input :photo, as: :file %>
<% end %>

<%= simple_form_for(transports) do |f| %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
<% end %>

app/views/transports/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="http://127.0.0.1:3000/">
    <img src ="https://res.cloudinary.com/dojiqdbe4/image/upload/v1677600746/diable1_wubyti.png">

</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <% if user_signed_in? %>
          <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %></a>
          <% else %>
          <%=link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          <% end %>
        </li>
          <li class="nav-item">
            <%= link_to 'Create Car', new_transport_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Tuning</a>
              <a class="dropdown-item" href="#">Dashbord</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Deconnect</a>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/transports/edit.html.erb
<h1>Modifier les photos existantes</h1>

<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for @transport do |f| %>
        <%= f.input :brand, placeholder: "Write the type of transport" %>
        <%= f.input :horse, placeholder: "Which power" %>
        <%= f.input :year, placeholder: "Year" %>
        <%= f.input :price, placeholder: "Price per day" %>
        <%# <%= f.input :photos, as: :file, input_html: { multiple: true }, :label => @transport.photos[0].key %>
        <%= f.submit "Submit list", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/transports/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
  <div class="container">
    <p><span class='text-align-center' data-controller="typed-js"></span></p>
  </div>
</div>

<div class='searchbar my-3'>
    <%= form_with url: root_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
      params[:query],
      class: "input",
      placeholder: "Find a turbo transport" %>
    <% end %>
</div>

<div class="container">
  <div class="cards-container">
    <% @transports.each do |transport| %>
      <div class="card">

        <% if transport.photos.attached? %>
          <% transport.photos.each do |photo| %>
              <%= cl_image_tag photo.key %>
          <% end %>
        <% else %>
        <%= 'No Image' %>
        <% end %>
        <div class="card-details">
          <h1><%= transport.brand %></h1>
          <p>Year : <%= transport.year %></p>
          <h2>Prix : <%= transport.price %> $</h2>
          <%= link_to 'Details', transport_path(transport.id), class: 'shadow__btn' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/transports/new.html.erb
<h1>Ajouter un moyen de transport de folie</h1>

<div class="container">
  <div class="row">
    <div class="col">
      <%= simple_form_for @transport do |f| %>
        <%= f.input :brand, placeholder: "Write the type of transport" %>
        <%= f.input :horse, placeholder: "Which power" %>
        <%= f.input :year, placeholder: "Year" %>
        <%= f.input :price, placeholder: "Price per day" %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <%= f.submit "Submit list", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<% @transport.photos.each do |photo| %>
  <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill %>
<% end %>

app/views/transports/show.html.erb
<h1>Transport - <%= @transport.brand %></h1>

<div class="container d-flex">
    <div class="card-product">
      <div class="card-image">
        <% if @transport.photos.attached? %>
          <% @transport.photos.each do |photo| %>
            <%= cl_image_tag photo.key, crop: :fill %>
          <% end %>
        <% else %>
          <%= 'No picture Available' %>
        <% end %>
      </div>
      <div class="card-product-infos">
          <h2> Brand : <%= @transport.brand %></h2>
          <p> Power : <%= @transport.horse %></p>
          <p> Year : <%= @transport.year %></p>
          <br>
          <br>
          <h2> Price per day : <%= @transport.price %> $</h2>
          <br>
          <br>
          <br>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda nobis consectetur voluptates ex officia maiores vel suscipit necessitatibus est sapiente. Neque, quibusdam. Ab pariatur animi excepturi cum omnis dolore nobis.</p>
      </div>
    </div>
</div>

<div class="containers">
  <div class="btn-home"><%= link_to 'Back to transports', root_path %></div>
  <div class="btn-home"> <%= link_to "Delete", transport_path(@transport.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %></div>
  <div class="btn-home"><%= link_to 'Book now', new_transport_booking_path(@transport.id) %></div>
</div>